import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
    lineHeight: 1.4,
    color: '#1F2937',
  },
  header: {
    marginBottom: 20,
    paddingBottom: 12,
    borderBottom: '2 solid #4F46E5',
  },
  title: {
    fontSize: 18,
    fontFamily: 'Helvetica-Bold',
    color: '#1F2937',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 10,
    color: '#6B7280',
  },
  metaRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 6,
  },
  metaBadge: {
    fontSize: 9,
    color: '#4F46E5',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
  },
  questionBlock: {
    marginBottom: 20,
    padding: 12,
    backgroundColor: '#F9FAFB',
    borderRadius: 6,
    borderLeft: '3 solid #4F46E5',
  },
  questionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
    gap: 6,
  },
  questionNumber: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#4F46E5',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 3,
    minWidth: 24,
    textAlign: 'center',
  },
  questionText: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: '#111827',
    flex: 1,
    lineHeight: 1.4,
  },
  sectionLabel: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: '#6B7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginTop: 6,
    marginBottom: 3,
  },
  answerText: {
    fontSize: 10,
    color: '#374151',
    lineHeight: 1.5,
  },
  tipBox: {
    marginTop: 8,
    padding: 7,
    backgroundColor: '#FFFBEB',
    borderRadius: 4,
    borderLeft: '2 solid #F59E0B',
  },
  tipLabel: {
    fontSize: 8,
    fontFamily: 'Helvetica-Bold',
    color: '#92400E',
    marginBottom: 2,
  },
  tipText: {
    fontSize: 9,
    color: '#78350F',
    lineHeight: 1.4,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: '#9CA3AF',
    borderTop: '1 solid #E5E7EB',
    paddingTop: 6,
  },
});

export default function InterviewQuestionsTemplate({
  questions = [],
  jobTitle,
  company,
  level,
  type,
}) {
  const levelLabel =
    { fresh: 'Entry Level', mid: 'Mid Level', senior: 'Senior Level' }[level] || level;
  const typeLabel =
    { technical: 'Technical', behavioural: 'Behavioural', mixed: 'Mixed' }[type] || type;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Interview Preparation Guide</Text>
          {(jobTitle || company) && (
            <Text style={styles.subtitle}>{[jobTitle, company].filter(Boolean).join(' · ')}</Text>
          )}
          <View style={styles.metaRow}>
            {level && <Text style={styles.metaBadge}>{levelLabel}</Text>}
            {type && <Text style={styles.metaBadge}>{typeLabel}</Text>}
            <Text style={styles.metaBadge}>{questions.length} Questions</Text>
          </View>
        </View>

        {questions.map((q, i) => (
          <View key={i} style={styles.questionBlock} wrap={false}>
            <View style={styles.questionHeader}>
              <Text style={styles.questionNumber}>Q{i + 1}</Text>
              <Text style={styles.questionText}>{q.question}</Text>
            </View>

            <Text style={styles.sectionLabel}>Model Answer</Text>
            <Text style={styles.answerText}>{q.answer}</Text>

            {q.tip && (
              <View style={styles.tipBox}>
                <Text style={styles.tipLabel}>Interviewer tip</Text>
                <Text style={styles.tipText}>{q.tip}</Text>
              </View>
            )}
          </View>
        ))}

        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages} · Generated by Job Application Tracker`
          }
          fixed
        />
      </Page>
    </Document>
  );
}
